### ISSUE TITLE
Not working with PHP-7.2

### ISSUE THREAD

**Issue by trueeh** [Opencast-Moodle/moodle-mod_opencast#7]
Moodle 3.8 requires minimum PHP 7.2 and Ubuntu 18.04 (LTS version supported until 2023) has PHP-7.2 but PHP-7.2 ist missing array_key_first() function:

Error : Call to undefined function mod_opencast\local\array_key_first()

Stack trace: 

    line 125 of /mod/opencast/classes/local/output_helper.php: Error thrown
    line 88 of /mod/opencast/view.php: call to mod_opencast\local\output_helper::output_episode()

**Comment by TamaraGunkel** [comment]
Hello,

thanks for pointing this out.
We decided to not support and test PHP 7.2 on purpose because it is end of live since last year and doesn't receive security updates anymore.
Thus, we strongly discourage using this version although it might be the minimum requirement for moodle 3.8.
The plugin should work fine with any higher PHP version and moodle 3.8.

However, if you really need the support for PHP 7.2, feel free to create a pull request that fixes this issue.

**Comment by trueeh** [comment]
Hello,

in Ubuntu 18.04 LTS the PHP version 7.2 will be supported until April 2023 ... so I would appreciate a hint in the system requirements.

We will migrate to Ubuntu 20.04 LTS soon, so I don't need it.

**Comment by TamaraGunkel** [comment]
Sure, that's reasonable. I've added the notice in the readme.
