### ISSUE TITLE
Add ability to pre-assign the series id and to select videos from repository plugin

### ISSUE THREAD

**Issue by trueeh** [Opencast-Moodle/moodle-mod_opencast#8]
The plugin does a great job, but the teachers often dont know what the "Opencast ID" is and where to get it.

It would be great if the series id of the course would be pre-assigned by default.

It would be great if the videos can be selected from the repository (opencast repository plugin).

**Comment by TamaraGunkel** [comment]
Hi,
thanks for your input. I can recommend to add activities using the block because then the series and video ID are automatically set.
But I can see that it would also be useful to simply the general form. 
Pre-assigning the series id is definitely something we can realize quite easily.
Selecting the videos requires more work but we'll consider it for the future.
And as always, we are happy if you contribute yourself by opening a pull request that adds these features!

**Comment by TamaraGunkel** [comment]
Hey,
I've added this functionality in a slightly different form. Using the repository isn't straightforward in this context. Thus, I've added select boxes. However, if there are many videos in a course, the UX might still be difficult. 
If there are going to be many complaints about that, I'm going think about another solution.
